feat(rich-text-editor): tests for rich text editor link extension and utils
dialpad/dialtone-vue pull request #1001
Opened 2023-05-29 20:58 UTC by MikaDialpad

# tests for rich text editor link extension and utils

## :hammer_and_wrench: Type Of Change

- [ ] Fix
- [x] Feature
- [ ] Refactoring
- [ ] Documentation

## :book: Description

Tests for rich text editor link extension, https://github.com/dialpad/dialtone-vue/pull/991

## :crystal_ball: Next Steps

Add the Vue3 version of the component with the tests.

## :link: Sources

https://github.com/dialpad/dialtone-vue/pull/991

2023-05-29 21:00 UTC, MikaDialpad commented on components/rich_text_editor/rich_text_editor.test.js
> +            expect(wrapper.emitted().input[0][0]).toEqual(output);
I came back to refactor this test now that I figured out a way to trigger actual value updates in the editor

2023-05-29 21:00 UTC, MikaDialpad commented on components/rich_text_editor/extensions/link/utils.js
> +  regex.lastIndex = 0;
Testing works! Found this bug right away when added tests for the method.

2023-05-30 17:22 UTC, braddialpad commented on components/rich_text_editor/extensions/link/utils.js
> +  regex.lastIndex = 0;
oh weird.

2023-05-30 18:12 UTC, braddialpad requested changes
Tests look really good, extremely well covered. My change requests are for Vitest related stuff you probably didn't know about.

2023-05-30 18:12 UTC, braddialpad commented on common/utils.test.js
> +  });
I just learned this existed myself, but these are perfect cases to use vitest's built in `test.each` instead of making multiple assertions within a single test.

https://vitest.dev/api/#test-each

2023-05-30 18:12 UTC, braddialpad commented on components/rich_text_editor/extensions/link/link.test.js
> +  };
While this was a valid way of doing things in mocha, I think it is really not recommended in Vitest. I know we still have tons of these in our codebase from our legacy tests and they still "run" (sort of), but it causes issues like the expect-expect you had to disable above and I know my IDE really hates them (hangs forever). I think at least going forward we should not continue to write them.

I believe the correct Vitest way to do this sort of thing if I'm not mistaken is to define a custom expect using `expect.extend`. see: https://vitest.dev/api/expect.html#expect-extend. I've not really used this myself yet so let me know if you run across any issues but it seems pretty straightforward.

2023-05-30 18:12 UTC, braddialpad commented on components/rich_text_editor/extensions/link/link.test.js
> +  };
Looks like some more details here as well https://vitest.dev/guide/extending-matchers.html

2023-05-31 18:57 UTC, iropolo commented on common/utils.test.js
> +  });
Hmm lemme see....

```
it('should not linkify non-URL content', async () => {
          test.each([
            ['check out dialpad,com it is cool'],
            ['check out dialpad com it is cool'],
            ['check out dialpadcom it is cool'],
            ['check out dialpad..com it is cool'],
            ['check out dialpad.comm it is cool'],
          ])('should not linkify non-URL content:', async (input) => {
            await _setValue(input);
            expectNoLinks();
          });
        });

        it('should linkify with valid content', async () => {
          test.each([
            ['check out dialpad.com it is cool', 'dialpad.com'],
            ['check out dialpad.com, and fspot.us!', 'dialpad.com', 'fspot.us'],
          ])('should linkify with valid content:', async (input, ...expectedLinks) => {
            await _setValue(input);
            expectLinksWithTexts(...expectedLinks);
          });
        });
```

I did this replacement, is this the approach?

<img width="1463" alt="image" src="https://github.com/dialpad/dialtone-vue/assets/89984179/1099cac4-c4a1-4102-8fc2-1cb50db87a37">

2023-05-31 19:11 UTC, braddialpad commented on common/utils.test.js
> +  });
Yep exactly.

2023-05-31 19:51 UTC, iropolo commented on components/rich_text_editor/extensions/link/link.test.js
> +  };
hmmm, it is something like this for `expectNoLinks`

```
expect.extend({
  toHaveNoLinks (received) {
    if (received.length === 0) {
      return {
        pass: true,
      };
    }
  },
});
```

```
it('should not linkify non-URL content', async () => {
          await _setValue('check out dialpad,com it is cool');
          expect(_getLinksFromJSON()).toHaveNoLinks();
          await _setValue('check out dialpad com it is cool');
          expect(_getLinksFromJSON()).toHaveNoLinks();
          await _setValue('check out dialpadcom it is cool');
          expect(_getLinksFromJSON()).toHaveNoLinks();
          await _setValue('check out dialpad..com it is cool');
          expect(_getLinksFromJSON()).toHaveNoLinks();
          await _setValue('check out dialpad.comm it is cool');
          expect(_getLinksFromJSON()).toHaveNoLinks();
        });
```

![Uploading image.png…]()

2023-06-06 21:03 UTC, MikaDialpad commented
Thanks for the tips @braddialpad, definitely made the tests feel and look more solid!

2023-06-06 22:14 UTC, braddialpad approved these changes
Looks great thanks!

2023-06-06 22:16 UTC, merged