fix(callbar-button-with-popover): show popover on demand and emit modal opened event
dialpad/dialtone-vue pull request #1031
Opened 2023-06-21 22:18 UTC by ramya-dp

# PR Title

show popover on demand and emit modal opened event

## :hammer_and_wrench: Type Of Change

- [X] Fix
- [ ] Feature
- [ ] Refactoring
- [ ] Documentation

## :book: Description

show popover on demand and emit modal opened event.

## :bulb: Context

show popover on demand and emit modal opened event. Required to auto open the Ai Assist panel. Ubervoice PR https://github.com/dialpad/firespotter/pull/30372

## :pencil: Checklist

- [X ] I have reviewed my changes
- [ ] I have added tests
- [X] I have added all relevant documentation
- [ ] I have validated components with a screen reader
- [ ] I have validated components keyboard navigation
- [ ] I have considered the performance impact of my change
- [ ] I have checked that my change did not significantly increase bundle size
- [ ] I am exporting any new components or constants in the index.js in the component directory
- [ ] I am exporting any new components or constants in the index.js in the root

## :camera: Screenshots / GIFs

No UI changed

2023-06-21 22:25 UTC, ramya-dp commented
@iropolo this is the vue3 version of https://github.com/dialpad/dialtone-vue/pull/1016. Requires approval before merge.

2023-06-22 16:31 UTC, iropolo requested changes
Seems to be all right but I can see this difference between the v2 version

<img width="653" alt="image" src="https://github.com/dialpad/dialtone-vue/assets/89984179/01dcbb85-b2d5-4c55-b74c-87f73363e949">

Seems like the 'button' text is at the left, not at the bottom as the v2 version if it is not correct could you update it please?

2023-06-22 16:33 UTC, braddialpad requested changes

2023-06-22 16:33 UTC, braddialpad commented on recipes/buttons/callbar_button_with_popover/callbar_button_with_popover_default.story.vue
> +    :open-popover="openPopover"
$attrs.openPopover

2023-06-22 17:13 UTC, ramya-dp commented
> Seems to be all right but I can see this difference between the v2 version
> 
> <img alt="image" width="653" src="https://user-images.githubusercontent.com/89984179/247996208-01dcbb85-b2d5-4c55-b74c-87f73363e949.png">
> Seems like the 'button' text is at the left, not at the bottom as the v2 version if it is not correct could you update it please?

@iropolo good catch! Seems like this is an existing issue - https://vue.dialpad.design/vue3/?path=/story/recipes-buttons-callbar-button-with-popover--default. Since it wasn't introduced in this PR I've created a Jira to address this separately https://dialpad.atlassian.net/browse/DP-73940.

2023-06-22 17:15 UTC, iropolo approved these changes
Okay cool! looks good 🚀

2023-06-22 17:36 UTC, ramya-dp commented
Merge is still blocked. I think @braddialpad needs to approve as well, please could you look at the updates?

2023-06-22 17:41 UTC, braddialpad approved these changes

2023-06-22 18:13 UTC, merged