feat: add avatar click event in contact info (vue3)
dialpad/dialtone-vue pull request #1165
Opened 2023-09-09 00:19 UTC by tonydialpad

## :hammer_and_wrench: Type Of Change

- [ ] Fix
- [x] Feature
- [ ] Refactoring
- [ ] Documentation

## :book: Description

This pull request adds `avatar-click` event in contact info component.

## :bulb: Context

When a user clicks on any of the avatars in the callbar when on a call with multiple other participants (i.e. a group call) it opens the “Manage participants” modal. To implement that, we need to add `avatar-click` event in contact info component.

## :pencil: Checklist

- [x] I have reviewed my changes
- [ ] I have added tests
- [x] I have added all relevant documentation
- [x] I have validated components with a screen reader
- [x] I have validated components keyboard navigation
- [x] I have considered the performance impact of my change
- [x] I have checked that my change did not significantly increase bundle size
- [ ] I am exporting any new components or constants in the index.js in the component directory
- [ ] I am exporting any new components or constants in the index.js in the root

## :crystal_ball: Next Steps

Make a new release for dialtone-vue

## :camera: Screenshots / GIFs
 No UI update

## :link: Sources

JIRA: https://dialpad.atlassian.net/browse/DP-71224
Vue2 PR: https://github.com/dialpad/dialtone-vue/pull/1164

2023-09-13 18:30 UTC, iropolo commented
Please update branch with changes in Vue2 version #1164

2023-09-13 18:31 UTC, iropolo requested changes
Please update branch with changes in Vue2 version #1164

2023-09-14 02:11 UTC, iropolo approved these changes
Thanks!

2023-09-14 15:36 UTC, braddialpad approved these changes

2023-09-14 17:05 UTC, merged