feat(modal): update danger style
dialpad/dialtone-vue pull request #583
Opened 2022-11-06 16:30 UTC by jimut-dialpad

# Update danger modal style

## :hammer_and_wrench: Type Of Change

- [ ] Fix
- [x] Feature
- [ ] Refactoring
- [ ] Documentation

## :book: Description

This is to make dialtone-vue's modal component match the styles of dialtone.

The corresponding change in dialtone was made in this PR https://github.com/dialpad/dialtone/pull/689

## :bulb: Context

To match modal styles of dialtone.

## :pencil: Checklist

- [x] I have reviewed my changes
- [ ] I have added tests
- [ ] I have added all relevant documentation
- [x] I have validated components with a screen reader
- [x] I have validated components keyboard navigation
- [x] I have considered the performance impact of my change
- [x] I have checked that my change did not significantly increase bundle size

## :camera: Screenshots / GIFs

![Screenshot 2022-11-06 at 9 56 20 PM](https://user-images.githubusercontent.com/79533776/200182450-2ae5f5e4-816b-4b8b-a485-839f03df85ec.png)

2022-11-07 17:27 UTC, braddialpad approved these changes

2022-11-07 19:27 UTC, francisrupert requested changes
Can we piggy-back on this update to correct the **button order.** Swap the button order on all variants, not just the danger variant. 

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/1165933/200397235-73f677f5-8780-4e21-afb0-79521ab11c03.png">

2022-11-08 13:45 UTC, jimut-dialpad commented
> Can we piggy-back on this update to correct the button order. Swap the button order on all variants, not just the danger variant.

Sure. Updated.

While we are at this. Should we also make the cancel button muted for all variants?
I think that makes it look more inline with our styles.

2022-11-08 19:12 UTC, francisrupert requested changes
Actually yeah, the "Cancel" button next to the danger/critical variant should be identical to all others. 

<img width="586" alt="image" src="https://user-images.githubusercontent.com/1165933/200653172-6855c9e6-d9b2-4288-b6e8-b0d70ca6108b.png">

Meanwhile, the buttons need breathing room between them. Add `d-ml6` to the far-right button.

<img width="655" alt="image" src="https://user-images.githubusercontent.com/1165933/200654217-2cd11fb1-ae28-445f-ba3f-ea4b171a3568.png">

2022-11-10 00:16 UTC, braddialpad requested changes
Hey Jimut, Francis meant the cancel button should be purple rather than muted. You can just remove the `kind` prop and it should fix it.

2022-11-10 04:53 UTC, jimut-dialpad commented
Got it. Sorry I thought otherwise. 
Updated.

2022-11-10 19:03 UTC, braddialpad approved these changes
Great thanks!

2022-11-11 06:44 UTC, merged