fix(recipe-callbar-btn): show tooltip when the callbar button is disa…
dialpad/dialtone-vue pull request #866
Opened 2023-03-28 18:38 UTC by ramya-dp

…bled

Show tooltip when the callbar button is disabled

## :hammer_and_wrench: Type Of Change

- [X] Fix
- [ ] Feature
- [ ] Refactoring
- [ ] Documentation

## :book: Description

Options to show tooltip text when the callbar recipe button is disabled

## :bulb: Context

Options to show tooltip text when the callbar recipe button is disabled
Jira: https://dialpad.atlassian.net/browse/DP-60576

## :pencil: Checklist

- [X ] I have reviewed my changes
- [ ] I have added tests
- [X] I have added all relevant documentation
- [ ] I have validated components with a screen reader
- [ ] I have validated components keyboard navigation
- [ ] I have considered the performance impact of my change
- [ ] I have checked that my change did not significantly increase bundle size
- [ ] I am exporting any new components or constants in the index.js in the component directory
- [ ] I am exporting any new components or constants in the index.js in the root

## :camera: Screenshots / GIFs
<img width="183" alt="Screen Shot 2023-03-28 at 11 36 40 AM" src="https://user-images.githubusercontent.com/70488122/228335448-7a322301-31fd-48c5-aa11-16d05b3f59a4.png">

2023-03-29 17:41 UTC, braddialpad requested changes

2023-03-29 17:41 UTC, braddialpad commented on recipes/buttons/callbar_button/callbar_button.vue
> +          :disabled="disabled"
The button is still functionally disabled, it's not accessible because you cannot tab to it to see the tooltip.

see the following dialtone guide: https://dialpad.design/components/button.html#disabled

in order to do this in an accessible way:

1. do not set the `disabled` prop
2. set class `d-btn--disabled` (you are already doing this)
3. set `aria-disabled="true"` on the button when disabled
4. wrap in `d-c-not-allowed` (you are already doing this)

2023-03-29 18:49 UTC, ramya-dp commented on recipes/buttons/callbar_button/callbar_button.vue
> +          :disabled="disabled"
thanks! updated - 

<img width="135" alt="Screen Shot 2023-03-29 at 11 48 04 AM" src="https://user-images.githubusercontent.com/70488122/228638410-c9f6c0e8-c8ad-4a4c-b4ec-3db75c589755.png">

2023-03-29 21:20 UTC, braddialpad reviewed
Do we need to make any updates to CallbarButtonWithPopover?

2023-03-29 21:22 UTC, braddialpad reviewed
I think this unit test is failing, which makes sense after this change. Probably can just update it to check for the class or aria-disabled instead.
```
it('Should display a disabled button when "disabled"', async function () {
  await wrapper.setProps({ disabled: true });
  assert.isTrue(button.element.disabled);
});
```

2023-03-29 21:32 UTC, ramya-dp commented
> it('Should display a disabled button when "

This is already working - 

<img width="227" alt="Screen Shot 2023-03-29 at 2 27 27 PM" src="https://user-images.githubusercontent.com/70488122/228672623-a9cff99b-aaa5-4930-a515-9d9bbb6294ca.png">

2023-03-29 22:02 UTC, braddialpad approved these changes

2023-03-30 20:54 UTC, ramya-dp commented
Vue3 branch was merged in https://github.com/dialpad/dialtone-vue/pull/873

2023-03-30 21:00 UTC, ramya-dp commented
@braddialpad I'm unable to merge this PR because of the check. The vue3 branch https://github.com/dialpad/dialtone-vue/pull/873 was already merged. 

Please could you help merge this PR?

2023-03-30 21:23 UTC, merged

2023-03-30 21:23 UTC, braddialpad commented
No problem, done

2023-03-30 21:30 UTC, ramya-dp commented
Thanks!