feat(header): add setting menu button with update option
dialpad/dialtone-vue pull request #937
Opened 2023-04-24 16:54 UTC by laurafirespotter

# Header settings menu button

## :hammer_and_wrench: Type Of Change

- [ ] Fix
- [X] Feature
- [ ] Refactoring
- [ ] Documentation

## :book: Description

Adds the header settings menu button with a variation if there is an app update available.

## :bulb: Context

This button is being added to Dialtone so it can be re-used in the new app.

## :pencil: Checklist

- [X] I have reviewed my changes
- [ ] I have added tests
- [X] I have added all relevant documentation
- [ ] I have validated components with a screen reader
- [X] I have validated components keyboard navigation
- [X] I am exporting any new components or constants in the index.js in the component directory
- [X] I am exporting any new components or constants in the index.js in the root

## :camera: Screenshots / GIFs

<img width="183" alt="Screen Shot 2023-04-24 at 11 48 22 AM" src="https://user-images.githubusercontent.com/9667058/234063059-628c426d-f35a-4222-9c92-1a180e38a9d6.png">
<img width="225" alt="Screen Shot 2023-04-24 at 11 48 44 AM" src="https://user-images.githubusercontent.com/9667058/234063142-091db40b-c428-4f4d-a744-11bd0159318a.png">

To replace

<img width="114" alt="Screen Shot 2023-04-24 at 11 53 05 AM" src="https://user-images.githubusercontent.com/9667058/234064083-1d1b59c6-2c7d-4f95-a99f-e924b9162499.png">

## :link: Sources

https://dialpad.atlassian.net/browse/DP-61587

2023-04-24 16:57 UTC, laurafirespotter commented on recipes/header/settings_menu_button/settings_menu_button.vue
> +.d-btn:active {
This doesn't feel like the right way to apply styling during a click, but I couldn't get the active prop to work.

2023-04-24 16:57 UTC, laurafirespotter commented on recipes/header/settings_menu_button/settings_menu_button_variants.story.vue
> +<template>
After coding this up I'm not sure that this recipe really has any variants? Left this here just in case but am happy to delete it.

2023-04-25 16:20 UTC, braddialpad commented on recipes/header/settings_menu_button/settings_menu_button_variants.story.vue
> +<template>
Yeah this component is pretty simple, not really necessary, you can just remove it

2023-04-25 17:01 UTC, braddialpad requested changes
Thanks! looking pretty good so far.

2023-04-25 17:01 UTC, braddialpad commented on recipes/header/settings_menu_button/settings_menu_button.vue
> +        class="d-bs-none d-fc-blue-500 d-ol-none d-svg--size20"
Not necessary to have `d-svg--size20` since you're already setting the `size="400"` prop

2023-04-25 17:01 UTC, braddialpad commented on recipes/header/settings_menu_button/settings_menu_button.vue
> +.d-btn:active {
Yeah I think the problem is we have no "active" utility classes like we do for hover / focus. Even if the active prop worked here it likely wouldn't give you the styling you want. This is okay for now.

2023-04-25 17:01 UTC, braddialpad commented on recipes/header/settings_menu_button/settings_menu_button_default.story.vue
> +    :update-available="updateAvailable"
need `aria-label` here too

2023-04-25 17:01 UTC, braddialpad commented on recipes/header/settings_menu_button/settings_menu_button.vue
> +        class="d-bs-none d-fc-blue-500 d-ol-none d-svg--size20"
`d-bs-none` an icon doesn't have a box-shadow does it? same with `d-ol-none`

2023-04-25 17:01 UTC, braddialpad commented on recipes/header/settings_menu_button/settings_menu_button.vue
> +    box-shadow: 0 0 0 var(--su2) hsla(var(--theme-sidebar-color-hsl) / .15);
the `su` variables are deprecated, you can replace `var(--su2)` with `var(--size-200)`

2023-04-25 17:01 UTC, braddialpad commented on recipes/header/settings_menu_button/settings_menu_button.mdx
> +### Complex
Can probably just title these "Default" and "Update Available"

2023-04-25 17:01 UTC, braddialpad commented on recipes/header/settings_menu_button/settings_menu_button.vue
> +.d-btn:active {
Is it intentional to have no active styling on the button when updateAvailable is false?

2023-04-25 17:01 UTC, braddialpad commented on recipes/header/settings_menu_button/settings_menu_button_default.story.vue
> +    :update-available="updateAvailable"
and `@click="onClick"` to trigger the action.

2023-04-25 21:18 UTC, laurafirespotter commented on recipes/header/settings_menu_button/settings_menu_button.vue
> +.d-btn:active {
Yes, that's per design. None of the header buttons in that style have active styling

2023-04-25 21:31 UTC, laurafirespotter commented
On my vue3 branch the buttons don't show up and I get a console warning - any ideas?

<img width="1771" alt="Screen Shot 2023-04-25 at 4 31 23 PM" src="https://user-images.githubusercontent.com/9667058/234408638-1b39f427-88f9-4dfa-b3c9-e823712d064f.png">

2023-04-26 16:58 UTC, braddialpad commented
> On my vue3 branch the buttons don't show up and I get a console warning - any ideas?

There's a couple things you always have to change on vue 3 so I'm guessing it's one of these:

In your default.story.vue add $attrs to each property like so:

before
```
:show-header="showHeader"
```

after
```
:show-header="$attrs.showHeader"
```

in your stories.js remove the argTypes from the template function like so:

before
```
const DefaultTemplate = (args, { argTypes }) => createTemplateFromVueFile(
  args,
  argTypes,
  DtCardDefaultTemplate,
);
```

after
```
const DefaultTemplate = (args) => createTemplateFromVueFile(
  args,
  DtCardDefaultTemplate,
);
```

2023-04-26 17:11 UTC, braddialpad approved these changes
Thanks! let me know if you need any help with the vue 3 branch.

2023-04-27 14:28 UTC, laurafirespotter commented
@braddialpad What is percy and do I need to fix that check before landing this? I don't have access to it currently.

2023-04-27 16:19 UTC, juliodialpad commented
> @braddialpad What is percy and do I need to fix that check before landing this? I don't have access to it currently.

Percy is our visual test suite, I just approved your changes, you're now good to go

2023-04-27 17:04 UTC, merged